version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: urlsnake-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - urlsnake-network
    environment:
      - MONGO_INITDB_DATABASE=urlsnake

  # URL Shortener web application
  webapp:
    build: .
    container_name: urlsnake-webapp
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - urlsnake-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=urlsnake
      - PORT=5000
      - HOST=0.0.0.0

networks:
  urlsnake-network:
    driver: bridge

volumes:
  mongodb_data:
